---
# tasks file for nodejs
    - name: create build directory
      file:
        path: "{{ nodejs_path }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    # at this point do not forget change DB_HOSenv variable for postgresql node
    - name: copy files to the nodejs node
      copy:
        src: ./server/
        dest: "{{ nodejs_path }}"

    - name: copy the dockerfile
      copy: 
        src: Dockerfile
        dest: "{{ nodejs_path }}"

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"

    - name: build container image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ nodejs_path }}"
        source: build
        state: present

    - name: create nodejs docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5000:5000"
