---
# tasks file for postgres
    - name: create build directory
      ansible.builtin.file:
        path: "{{ postgres_path }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      
    # https://stackoverflow.com/questions/35487756/how-to-copy-files-with-ansible-relatively-to-the-role
    - name: copy the sql script
      copy:
        src: init.sql
        dest: "{{ postgres_path }}"

    - name: copy dockerfile
      copy: 
        src: Dockerfile
        dest: "{{ postgres_path }}"

    - name: remove container and image if exist
      shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"

    - name: build container image
      docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ postgres_path }}"
        source: build
        state: present     

    - name: create postgresql docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "Pp123456789"
        volumes:
          - /db-data:/var/lib/postgresql/data
